#!/usr/bin/env bash

set -e

LD=arm-none-eabi-ld
OBJCOPY=arm-none-eabi-objcopy

echo "Building archive..."
echo "  - ld: $LD"
echo "  - objcopy: $OBJCOPY"
echo "  - arguments: $@"

OUTPUT="$1"
shift 1
rm -f "${OUTPUT}"

POS=0

while [ ! -z "$1" ]; do
  # Remove the suffix from $1
  FILENAME="$(echo "$1" | sed -e 's/_flash//')"
  # If filename doesn't exist, interpret it as a application name
  if [ ! -f "$FILENAME" ]; then
    NAME="$1"
    FILENAME="apps/$FILENAME/app.elf"
  fi
  NAME="$(basename $(dirname "$FILENAME"))"
  echo "  - $FILENAME"
  sed "s/\+ (0)/+ (${POS})/" apps/external.ld > temp.ld
  "${LD}" "$FILENAME" -o "${NAME}_linked.elf" -Ttemp.ld
  "${OBJCOPY}" -O binary "${NAME}_linked.elf" "${NAME}"
  tar -rf "${OUTPUT}" "${NAME}"
  POS=$(( ${POS} + (($(stat --printf="%s" "${NAME}") + 1023)/512)*512 ))
  rm -f temp.ld "${NAME}" "${NAME}_linked.elf"
  shift 1
done
